services:
  mongodb:
    image: mongo:7
    container_name: football_mongodb
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: football_store
      MONGO_INITDB_ROOT_USERNAME: ecom_admin
      MONGO_INITDB_ROOT_PASSWORD: holamundo
      TZ: America/La_Paz
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: football_mongo_express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ecom_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: holamundo
      ME_CONFIG_BASICAUTH: 'false'

  postgres:
    image: postgres:15
    container_name: football_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: football_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/La_Paz
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mongo_data:
  postgres_data: