db = db.getSiblingDB('football_store')

if (!db.getCollectionNames().includes('products')) {
  db.createCollection('products')
}

db.products.createIndex({ slug: 1 }, { unique: true })
db.products.createIndex({ category: 1, featured: -1, createdAt: -1 })
db.products.createIndex({ brand: 1 })
db.products.createIndex({ searchKeywords: 1 })
db.products.createIndex({ active: 1, stock: 1 })

const products = [
  {
    slug: 'training-ball-pro',
    sku: 'TBG-001',
    name: 'Training Ball Pro',
    category: 'equipment',
    price: 49.99,
    image: '/products/ball.svg',
    description: 'Durable ball for daily training on natural or synthetic grass.',
    tags: ['ball', 'training'],
    searchKeywords: ['ball', 'training', 'equipment', 'pro'],
    brand: 'ProSport',
    featured: true,
    active: true,
    stock: 24,
    rating: 4.8,
    reviewsCount: 128,
    currency: 'BOB',
    gallery: ['/products/ball.svg'],
    attributes: { material: 'PU', size: 5, weight_g: 410 },
    specs: { material: 'PU', size: 5, weight_g: 410, use: 'daily training' },
    createdAt: new Date(),
  },
  {
    slug: 'speed-cleats',
    sku: 'SPD-002',
    name: 'Speed Cleats',
    category: 'footwear',
    price: 279.99,
    image: '/products/boots.svg',
    description: 'Lightweight cleats for acceleration and fast direction changes.',
    tags: ['cleats', 'speed'],
    searchKeywords: ['cleats', 'speed', 'boots', 'footwear'],
    brand: 'FastKick',
    featured: true,
    active: true,
    stock: 18,
    rating: 4.9,
    reviewsCount: 84,
    currency: 'BOB',
    gallery: ['/products/boots.svg'],
    attributes: { sizes: [40, 41, 42, 43], material: 'synthetic', surface: 'firm' },
    specs: { sizes: [40, 41, 42, 43], material: 'synthetic', surface: 'firm' },
    createdAt: new Date(),
  },
  {
    slug: 'performance-boots',
    sku: 'CTL-003',
    name: 'Performance Boots',
    category: 'footwear',
    price: 249.99,
    image: '/products/boots.svg',
    description: 'Control-focused boots with match-ready traction outsole.',
    tags: ['cleats', 'control'],
    searchKeywords: ['boots', 'control', 'footwear', 'traction'],
    brand: 'ControlMax',
    featured: false,
    active: true,
    stock: 11,
    rating: 4.7,
    reviewsCount: 56,
    currency: 'BOB',
    gallery: ['/products/boots.svg'],
    attributes: { sizes: [39, 40, 41, 42], material: 'leather', surface: 'soft' },
    specs: { sizes: [39, 40, 41, 42], material: 'leather', surface: 'soft' },
    createdAt: new Date(),
  },
  {
    slug: 'away-jersey-pro',
    sku: 'JRS-004',
    name: 'Away Jersey Pro',
    category: 'apparel',
    price: 94.99,
    image: '/products/jersey.svg',
    description: 'Official jersey with athletic fit and breathable fabric.',
    tags: ['jersey', 'kit'],
    searchKeywords: ['jersey', 'kit', 'apparel', 'match'],
    brand: 'TeamWear',
    featured: true,
    active: true,
    stock: 31,
    rating: 4.6,
    reviewsCount: 103,
    currency: 'BOB',
    gallery: ['/products/jersey.svg'],
    attributes: { sizes: ['S', 'M', 'L', 'XL'], material: 'polyester', fit: 'athletic' },
    specs: { sizes: ['S', 'M', 'L', 'XL'], material: 'polyester', fit: 'athletic' },
    createdAt: new Date(),
  },
  {
    slug: 'keeper-gloves-elite',
    sku: 'GLV-005',
    name: 'Keeper Gloves Elite',
    category: 'equipment',
    price: 79.99,
    image: '/products/gloves.svg',
    description: 'Goalkeeper gloves with premium grip in dry or wet conditions.',
    tags: ['gloves', 'keeper'],
    searchKeywords: ['gloves', 'keeper', 'goalkeeper', 'equipment'],
    brand: 'GripPro',
    featured: false,
    active: true,
    stock: 14,
    rating: 4.5,
    reviewsCount: 67,
    currency: 'BOB',
    gallery: ['/products/gloves.svg'],
    attributes: { sizes: ['S', 'M', 'L'], palm: 'latex', weather: ['dry', 'wet'] },
    specs: { sizes: ['S', 'M', 'L'], palm: 'latex', weather: ['dry', 'wet'] },
    createdAt: new Date(),
  },
  {
    slug: 'training-cone-kit',
    sku: 'TRN-006',
    name: 'Training Cone Kit',
    category: 'training',
    price: 34.99,
    image: '/products/training.svg',
    description: 'Cone set for speed and coordination drills.',
    tags: ['cones', 'training'],
    searchKeywords: ['cones', 'training', 'drills', 'speed'],
    brand: 'DrillMaster',
    featured: false,
    active: true,
    stock: 40,
    rating: 4.4,
    reviewsCount: 49,
    currency: 'BOB',
    gallery: ['/products/training.svg'],
    attributes: { pieces: 20, color: ['orange', 'yellow'] },
    specs: { pieces: 20, color: ['orange', 'yellow'] },
    createdAt: new Date(),
  },
  {
    slug: 'bib-vest-pack',
    sku: 'TRN-007',
    name: 'Bib Vest Pack',
    category: 'training',
    price: 29.99,
    image: '/products/training.svg',
    description: 'Training bib pack to split teams during sessions.',
    tags: ['vests', 'training'],
    searchKeywords: ['vests', 'training', 'bib', 'sessions'],
    brand: 'DrillMaster',
    featured: false,
    active: true,
    stock: 35,
    rating: 4.3,
    reviewsCount: 42,
    currency: 'BOB',
    gallery: ['/products/training.svg'],
    attributes: { pieces: 10, sizes: ['adult'] },
    specs: { pieces: 10, sizes: ['adult'] },
    createdAt: new Date(),
  },
  {
    slug: 'match-socks-pro',
    sku: 'APP-008',
    name: 'Match Socks Pro',
    category: 'apparel',
    price: 19.99,
    image: '/products/socks.svg',
    description: 'Match socks with light compression and arch support.',
    tags: ['socks', 'kit'],
    searchKeywords: ['socks', 'kit', 'apparel', 'compression'],
    brand: 'SockIt',
    featured: false,
    active: true,
    stock: 64,
    rating: 4.2,
    reviewsCount: 31,
    currency: 'BOB',
    gallery: ['/products/socks.svg'],
    attributes: { sizes: ['S', 'M', 'L'], material: 'nylon' },
    specs: { sizes: ['S', 'M', 'L'], material: 'nylon' },
    createdAt: new Date(),
  },
  {
    slug: 'smartphone-vision-5',
    sku: 'ELE-101',
    name: 'Smartphone Vision 5',
    category: 'electronics',
    price: 899.99,
    image: '/products/phone.svg',
    description: '5G smartphone with OLED display and triple camera.',
    tags: ['phone', 'mobile', '5g'],
    searchKeywords: ['phone', 'electronics', 'mobile', '5g'],
    brand: 'VisionTech',
    featured: true,
    active: true,
    stock: 22,
    rating: 4.7,
    reviewsCount: 215,
    currency: 'BOB',
    gallery: ['/products/phone.svg'],
    attributes: { storage_gb: [128, 256], ram_gb: [8, 12], color: ['black', 'blue'] },
    specs: { display: '6.5 OLED', battery_mah: 4800, connectivity: ['5G', 'Wi-Fi 6'] },
    createdAt: new Date(),
  },
  {
    slug: 'ergonomic-chair-pro',
    sku: 'HOM-202',
    name: 'Ergonomic Chair Pro',
    category: 'furniture',
    price: 459.99,
    image: '/products/chair.svg',
    description: 'Ergonomic office chair with lumbar support and adjustable armrests.',
    tags: ['chair', 'office', 'comfort'],
    searchKeywords: ['chair', 'furniture', 'office', 'ergonomic'],
    brand: 'HomeForge',
    featured: false,
    active: true,
    stock: 16,
    rating: 4.6,
    reviewsCount: 87,
    currency: 'BOB',
    gallery: ['/products/chair.svg'],
    attributes: { material: 'mesh', color: ['gray', 'black'], max_weight_kg: 120 },
    specs: { lumbar_support: true, tilt_lock: true, armrests: 'adjustable' },
    createdAt: new Date(),
  },
  {
    slug: 'nonstick-pan-28',
    sku: 'KIT-303',
    name: 'Nonstick Pan 28cm',
    category: 'kitchen',
    price: 119.99,
    image: '/products/pan.svg',
    description: '28 cm nonstick pan for everyday cooking and quick cleanup.',
    tags: ['pan', 'cookware', 'kitchen'],
    searchKeywords: ['pan', 'kitchen', 'cookware', 'nonstick'],
    brand: 'KitchenCraft',
    featured: true,
    active: true,
    stock: 48,
    rating: 4.8,
    reviewsCount: 142,
    currency: 'BOB',
    gallery: ['/products/pan.svg'],
    attributes: { diameter_cm: 28, material: 'aluminum', coating: 'nonstick' },
    specs: { compatible_stoves: ['gas', 'electric', 'induction'], dishwasher_safe: true },
    createdAt: new Date(),
  },
  {
    slug: 'ambient-led-lamp',
    sku: 'DEC-404',
    name: 'Ambient LED Lamp',
    category: 'decor',
    price: 89.99,
    image: '/products/lamp.svg',
    description: 'Warm LED lamp for home decor and bedside lighting.',
    tags: ['lamp', 'decor', 'light'],
    searchKeywords: ['lamp', 'decor', 'lighting', 'home'],
    brand: 'AuraHome',
    featured: false,
    active: true,
    stock: 33,
    rating: 4.5,
    reviewsCount: 64,
    currency: 'BOB',
    gallery: ['/products/lamp.svg'],
    attributes: { color_temperature: ['warm', 'neutral'], height_cm: 42 },
    specs: { power_w: 12, dimmable: true, socket: 'E27' },
    createdAt: new Date(),
  },
]

if (db.products.countDocuments() === 0) {
  db.products.insertMany(products)
}